bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views
app_name= 'images'
urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('ranking/', views.image_ranking, name='ranking')
]

images/models.py
from dataclasses import field
from email.policy import default
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils.text import slugify


# Create your models here.
class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField(max_length=250)
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)
    # Chapter 7 - denormalizing counts
    total_likes = models.PositiveIntegerField(default=0)

    class Meta:
        #https://docs.djangoproject.com/en/4.1/ref/models/options/#django.db.models.Options.indexes
        indexes = [
            models.Index(fields=['-created']),
            models.Index(fields=['-total_likes'])
        ]
        ordering = ['-created']
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    # common pattern for providing canonical URLs for objects is to define a get_
    #absolute_url() method in the model.
    def get_absolute_url(self):
        return reverse("images:detail", args=[self.id, self.slug])
    
    
    def __str__(self) -> str:
        return self.title

images/forms.py
import requests
from django import forms
from django.core.files.base import ContentFile
from django.utils.text import slugify
from .models import Image

class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['title','url','description']
        widgets = {
            'url': forms.HiddenInput
        }

    def clean_urls(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg','jpeg','png']

        extension = url.rsplit('.',1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions')
        
        return url

    '''
    We have overridden the save() method, keeping the parameters required by ModelForm. The preceding 
    code can be explained as follows:
    1. A new image instance is created by calling the save() method of the form with commit=False.
    2. The URL of the image is retrieved from the cleaned_data dictionary of the form.
    3. An image name is generated by combining the image title slug with the original file extension 
    of the image.
    4. The Requests Python library is used to download the image by sending an HTTP GET request 
    using the image URL. The response is stored in the response object.
    5. The save() method of the image field is called, passing it a ContentFile object that is instatiated with the downloaded file content. 
    In this way, the file is saved to the media directory of the project. 
    The save=False parameter is passed to avoid saving the object to the database yet.
    6. To maintain the same behavior as the original save() method of the model form, the form is 
    only saved to the database if the commit parameter is True.
    '''
    
    def save(self, force_insert=False, force_update=False, commit=True):
        image = super().save(commit=False) #1
        image_url = self.cleaned_data['url'] #2
        name = slugify(image.title) #3
        extension = image_url.rsplit('.',1)[1].lower()
        image_name = f'{name}.{extension}'

        #Download image from the given url
        response = requests.get(image_url) #4
        image.image.save(image_name, ContentFile(response.content), save=False) #5

        if commit: #6, if commit is True
            image.save()
        return image

images/views.py
from cProfile import label
import redis
from django.conf import settings
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import HttpResponse, JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from .forms import ImageCreateForm
from .models import Image
#Chapter 7
from actions.utils import create_action

# Create your views here.

# Connect with redis
r = redis.Redis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)

'''
This is how 
this view works:
1. Initial data has to be provided through a GET HTTP request in order to create an instance of 
the form. This data will consist of the url and title attributes of an image from an external 
website. Both parameters will be set in the GET request by the JavaScript bookmarklet that we 
will create later. For now, we can assume that this data will be available in the request.
2. When the form is submitted with a POST HTTP request, it is validated with form.is_valid(). 
If the form data is valid, a new Image instance is created by saving the form with form.
save(commit=False). The new instance is not saved to the database because of commit=False.
3. A relationship to the current user performing the request is added to the new Image instance 
with new_image.user = request.user. This is how we will know who uploaded each image.
4. The Image object is saved to the database.
5. Finally, a success message is created using the Django messaging framework and the user 
is redirected to the canonical URL of the new image. We havent yet implemented the get_
absolute_url() method of the Image model;
'''

@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST) # (2)
        if form.is_valid():                       # (2)
            cd = form.cleaned_data
            new_image = form.save(commit=False)   #2

            # assign current user to the item
            new_image.user = request.user         # (3)
            # save new image
            new_image.save()                      # (4)

            # use action (chapter 7, p.305)
            create_action(request.user,"bookmarked image", new_image)
            #Success message
            messages.success(request,'Image added successfully')  #(5)

            # Redirect to new created item detail view
            return redirect(new_image.get_absolute_url())
    else:
        # build form with data provided by the bookmarklet via GET
        form = ImageCreateForm(data=request.GET)
    return render(request, 'images/image/create/html', {'section': 'images', 'form': form})


def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug )
    
    # Chapter 7 - Count images view with redis
    # incr là hàm của redis, mang nghĩa increment. 
    # You store the value in the total_views variable and pass it into the template context. 
    # You build the Redis key using a notation such as object-type:id:field (for example, image:33:id)
    total_views = r.incr(f'image:{image.id}:views')

    # Storing a ranking in Redis

    r.zincrby('image_ranking',1,image.id)
    return render(request, 'images/image/detail.html', {'section': 'images', 'image': image, 'total_views': total_views})

@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')

    images_only = request.GET.get('images_only') # GET parameter images_only to know if the whole page has to be rendered or only the new images when scrolling
    try:
        images = paginator.page(page)
    
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        images = paginator.page(1)
    except EmptyPage:
        if images_only:
            # If ajax request and page out of range
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)
    
    if images_only:
        return render(request, 'images/image/list_images.html', {'section': 'images', 'images': images})
    
    return render(request, 'images/image/list.html', {'section': 'images', 'images': images})

'''
The require_POST decorator returns an HttpResponseNotAllowed
object (status code 405) if the HTTP request is not done via POST. This way, you only allow POST requests for this view.
'''

'''
If the add() method is called passing an object that is already present in the related object set, it will 
not be duplicated. If the remove() method is called with an object that is not in the related object set, 
nothing will happen. Another useful method of many-to-many managers is clear(), which removes 
all objects from the related object set.
'''

'''
To generate the view response, we have used the JsonResponse class provided by Django, which 
returns an HTTP response with an application/json content type, converting the given object into 
a JSON output.
'''

@login_required
@require_POST

def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')

    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, "likes",image)
            else:
                image.users_like.remove(request.user)
        except Image.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})

# CHapter 7 - Store ranking with Redis
'''
The image_ranking view works like this:
1. You use the zrange() command to obtain the elements in the sorted set. This command expects 
a custom range according to the lowest and highest scores. Using 0 as the lowest and -1 as the 
highest score, you are telling Redis to return all elements in the sorted set. You also specify 
desc=True to retrieve the elements ordered by descending score. Finally, you slice the results 
using [:10] to get the first 10 elements with the highest score.
2. You build a list of returned image IDs and store it in the image_ranking_ids variable as a list 
of integers. You retrieve the Image objects for those IDs and force the query to be executed 
using the list() function. It is important to force the QuerySet execution because you will 
use the sort() list method on it (at this point, you need a list of objects instead of a QuerySet).
3. You sort the Image objects by their index of appearance in the image ranking. Now you can use 
the most_viewed list in your template to display the 10 most viewed images.
'''
@login_required
def image_ranking(request):
    image_ranking = r.zrange('image_ranking',0,-1,desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]

    #get most viewed images
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x:image_ranking_ids.index(x.id))
    return render(request, 'images/image/ranking.html', {'section': 'images', 'most_viewed': most_viewed})

images/templates/images/image/create.html
{% extends 'base.html' %}

{% block title %}
    Bookmark an image
{% endblock title %}

{% block content %}
<h1>Bookmark an image</h1>
<img src={{ request.GET.url }} class="image-preview" />
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Bookmark it!"
</form>
{% endblock content %}

images/templates/images/image/detail.html
{% extends 'base.html' %} 
{% block title %} 
    {{ image.title }} 
{% endblock title%} 
{% block content %}
<h1>{{ image.title }}</h1>
<img src="{{image.image.url}}" class="image-detail" />
{% with total_likes=image.users_like.count users_like=image.users_like.all %}
<div class="image-info">
  <div>
    <span class="count">
      <span class="total">{{ total_likes}}</span>
      like{{total_likes|pluralize}}
    </span>
    <span class="count">
      {{ total_views }} view{{ total_views|pluralize }}
    </span>
    <a
      href="#"
      data-id="{{ image.id }}"
      data-action="{% if request.user in users_like %}un{% endif %}like"
      class="like button"
    >
      {% if request.user not in users_like %} Like {% else %} Unlike {% endif %}
    </a>
  </div>
  {{ image.description|linebreaks }}
</div>
<div class="image-likes">
    {% for user in users_like %}
        <div>
            {% if user.profile.photo %}
                <img src="{{ user.profile.photo.url }}"
            {% endif %}
            <p> {{ user.first_name}}</p>
        </div>
        {% empty %}
        Nobody likes this image yet
    {% endfor %}
</div>
{% endwith %} {% endblock content %}
{% block domready %}
    const url = '{% url 'images:like' %}'
    var options = {
        method: 'POST',
        headers: {'X-CSRFToken': csrftoken },
        mode: 'same-origin'
    }

    document.querySelector('a.like').addEventListener('click', function(e) {
        e.preventDefault(); 
        var likeButton = this;

        var formData = new FormData();
        formData.append('id', likeButton.dataset.id);
        formData.append('action', likeButton.dataset.action)
        options['body'] = formData;

        fetch(url, options)
        .then (response=> response.json())
        .then (data=> {
            if (data['status'] === 'ok') {
                var previousAction = likeButton.dataset.action;

                var action = previousAction === 'like' ? 'unlike' : 'like';
                likeButton.dataset.action = action;
                likeButton.innerHTML = action;

                var likeCount = document.querySelector('span.count .total');
                var totalLikes = parseInt(likeCount.innerHTML);

                likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;
            }
        })
    });
{% endblock domready %}

images/templates/images/image/list.html
{% extends 'base.html' %}

{% block title %}Images Bookmarked{% endblock title %}
{% block content %}
    <h1>Images bookmarked</h1>
    <div id="image-list">
        {% include 'images/image/list_images.html' %}
    </div>
{% endblock content %}

{% block domready %}
    const page = 1;
    const emptyPage = false;
    const blockRequest = false;
    window.addEventListener('scroll', function(e) {
        let margin = document.body.clientHeight - window.innerHeight - 200;
        if(window.pageYOffset > margin && !emptyPage && !blockRequest) {
            blockRequest = true;
            page += 1;
            fetch('?images_only=1&page' + page)
            .then(response=> response.text())
            .then(html=> {
                if(html === '') {
                    emptyPage = true;
                }
                else {
                    var imageList = document.getElementById('image-list');
                    imageList.insertAdjacentHTML('beforeEnd',html);
                    blockRequest = false;
                }
            })
        }
    });
    const scrollEvent = new Event('scroll');
    window.dispatchEvent(scrollEvent)
{% endblock domready %}

images/templates/images/image/list_images.html
{% load thumbnail %}
{% for image in  images%}
    <div class="image">
        <a href="{{image.get_absolute_url }}">
            {% thumbnail image.image 300x300 crop="smart" as im %}
            <a href="{{ image.get_absolute_url }}">
                <img src="{{ im.url }}" />
            </a>
        </a>
        <div class="info">
            <a href="{{ image.get_absolute_url}}" class="title">
                {{ image.title }}
            </a> 
        </div>
    </div>
{% endfor %}

images/templates/images/image/ranking.html
{% extends 'base.html' %}
{% block title %}Images Ranking{% endblock title %}

{% block content %}
    <h1>Images Ranking</h1>
    <ol>
        {% for image in  most_viewed%}
            <li>
                <a href="{{ image.get_absolute_url }}">
                    {{ image.title }}
                </a>
            </li>
        {% endfor %}
    </ol>
{% endblock content %}